FORMAT: 1A

# Rails + Dredd proof of concept

# Posts [/posts]

## Creating a POST [POST]

+ Request (application/json)
    + Headers

            Accept: application/json
            Content-Length: 92

    + Body

            {
                "post": {
                    "title": "My post title",
                    "content": "Some content"
                }
            }

+ Response 201

  ```
  {
    "title": "My post title",
    "content": "Some content",
    "created_at": "2013-11-01T16:18:08.275Z",
    "updated_at":"2013-11-01T16:18:08.275Z"
  }
  ```  
